#! /usr/local/bin/python

import cgi, smtplib

LISTS = ["announce", "misc"]
TYPES = ["subscribe", "subscribe-digest", "unsubscribe", "help"]
TYPES_MAP = {"subscribe" : "Sent subscription e-mail to ", "subscribe-digest" : "Sent digest subscription e-mail to ", "unsubscribe" : "Sent unsubscription e-mail to ", "help" : "Sent help e-mail to "}



def main():

	form = cgi.FieldStorage()
	if not (form.has_key("list") and form["list"].value in LISTS and form.has_key("type") and form["type"].value in TYPES):
		print "Incorrect parameters. Aborting."
		return

	if not form.has_key("email"):
		print "You must specify an e-mail address."
		return

	list = form["list"].value
	type = form["type"].value
	email = form["email"].value

	list_email = "%s+%s@convergepl.org" % (list, type)

	msg = """From: %s
To: %s
Subject:

""" % (email, list_email)

	server = smtplib.SMTP('localhost')
	server.sendmail(email, list_email, msg)
	server.quit()

	print "%s%s." % (TYPES_MAP[type], email)


if __name__ == "__main__":
	main()

